server:
  port: 8087

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/kizuna-audit
  mongodb:
    uri: mongodb://mongo:27017/kizuna-audit
  rabbitmq:
    host: rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://kizuna-keycloak:8080/realms/Kizuna/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
