server:
  port: 8082

kizuna:
  iam:
    base-url: http://localhost:8083

spring:
  application:
    name: core-service

  datasource:
    url: jdbc:postgresql://localhost:5432/kizuna?currentSchema=core
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: core


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/Kizuna
          jwk-set-uri: http://localhost:8081/realms/Kizuna/protocol/openid-connect/certs

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

resilience4j:
  circuitbreaker:
    instances:
      iamService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      iamService:
        timeoutDuration: 3s

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "always"