spring.application.name=Kizuna-core-service
server.servlet.context-path=/core
kizuna.iam.base-url=http://kizuna-iam-service:8083
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://kizuna-keycloak:8080/realms/Kizuna/protocol/openid-connect/certs

management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
