spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - RemoveRequestHeader=Origin
      routes:
        # Keycloak (links de e-mail UPDATE_PASSWORD costumam apontar para :8080)
        - id: keycloak-realms
          uri: http://kizuna-keycloak:8080
          predicates:
            - Path=/realms/**
        - id: keycloak-resources
          uri: http://kizuna-keycloak:8080
          predicates:
            - Path=/resources/**
        - id: kizuna-core-service
          uri: http://kizuna-core-service:8082
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=0
        - id: ai-service
          uri: http://kizuna-ai-service:8090
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=0
        - id: iam-service
          uri: http://kizuna-iam-service:8083
          predicates:
            - Path=/iam/**
          filters:
            - StripPrefix=1
        - id: data-service
          uri: http://kizuna-data-service:8085
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://kizuna-notification-service:8086
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
        - id: audit-service
          uri: http://kizuna-audit-service:8087
          predicates:
            - Path=/audit/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
