server:
  port: 8085

spring:
  application:
    name: data-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/kizuna-data

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/Kizuna
          jwk-set-uri: http://localhost:8081/realms/Kizuna/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always